
-----------------------------------
        /*CICLO 1: XTablas*/
-----------------------------------
DROP TABLE participante CASCADE CONSTRAINTS;
DROP TABLE telefono CASCADE CONSTRAINTS;
DROP TABLE solicitud CASCADE CONSTRAINTS;
DROP TABLE oferta CASCADE CONSTRAINTS;
DROP TABLE actualizacion CASCADE CONSTRAINTS;
DROP TABLE factorMatch CASCADE CONSTRAINTS;
DROP TABLE operador CASCADE CONSTRAINTS;
DROP TABLE area CASCADE CONSTRAINTS;
DROP TABLE condicion CASCADE CONSTRAINTS;
DROP TABLE estrato CASCADE CONSTRAINTS;
DROP TABLE extra CASCADE CONSTRAINTS;
DROP TABLE habitacion CASCADE CONSTRAINTS;
DROP TABLE inmueble CASCADE CONSTRAINTS;
DROP TABLE tipoPiso CASCADE CONSTRAINTS;
DROP TABLE tipoOferta CASCADE CONSTRAINTS;
DROP TABLE ubicacion CASCADE CONSTRAINTS;
DROP TABLE antiguedad CASCADE CONSTRAINTS;