---------------------------------------------------------------------------------------------------------------------------
                                              /*CICLO 1: CRUDE*/
---------------------------------------------------------------------------------------------------------------------------

/*PROPUESTA*/
CREATE OR REPLACE PACKAGE PC_PROPUESTAS IS
  PROCEDURE AD_PROPUESTA (xtid IN CHAR, xnid IN NUMBER, xpropuesta IN VARCHAR2, xid_negocio IN NUMBER);
  PROCEDURE MO_PROPUESTA (xnumero IN NUMBER, xpropuesta IN VARCHAR2);
  FUNCTION CO_PROPUESTA RETURN SYS_REFCURSOR;
END PC_PROPUESTAS;
/

/*NEGOCIO*/
CREATE OR REPLACE PACKAGE PC_NEGOCIOS IS
  PROCEDURE AD_NEGOCIO (xpropietario IN VARCHAR, xtitularidad IN VARCHAR, xuso IN VARCHAR, xfruto IN VARCHAR, xestadoJuridico IN XMLTYPE, xid_seguimiento IN NUMBER);
  PROCEDURE MO_NEGOCIO (xid_negocio IN NUMBER, xestadoJuridico IN XMLTYPE);
  FUNCTION CO_NEGOCIO RETURN SYS_REFCURSOR;
  FUNCTION CO_ESTADO_JURIDICO RETURN SYS_REFCURSOR;
END PC_NEGOCIOS;
/

/*DOCUMENTO*/
CREATE OR REPLACE PACKAGE PC_DOCUMENTOS IS 
  PROCEDURE AD_DOCUMENTO (ximagen IN VARCHAR);
  PROCEDURE AD_PROMESA (xnumero IN NUMBER, xinmueble IN VARCHAR, xid_comprador NUMBER, xid_vendedor NUMBER);
  PROCEDURE AD_ESCRITURA (xnumero IN NUMBER, xevento IN CHAR);
  PROCEDURE MO_DOCUMENTO (xnumero IN NUMBER);
  PROCEDURE EL_DOCUMENTO (xnumero IN NUMBER);
  FUNCTION CO_DOCUMENTO RETURN SYS_REFCURSOR;
  FUNCTION CO_PROMESA RETURN SYS_REFCURSOR;
  FUNCTION CO_ESCRITURA RETURN SYS_REFCURSOR;
END PC_DOCUMENTOS ;
/

/*SEGUIMIENTO*/
CREATE OR REPLACE PACKAGE PC_SEGUIMIENTOS IS 
  PROCEDURE AD_SEGUIMIENTO (xdocumento IN NUMBER, xfechafin DATE, xporcentaje IN NUMBER);
  PROCEDURE MO_SEGUIMIENTO (xid_seguimiento IN NUMBER, xporcentaje IN NUMBER);
  PROCEDURE EL_SEGUIMIENTO (xid_seguimiento IN NUMBER);
  FUNCTION CO_SEGUIMIENTO RETURN SYS_REFCURSOR;
  FUNCTION CO_SEG_POR RETURN SYS_REFCURSOR;
  FUNCTION CO_ACTIVO RETURN SYS_REFCURSOR;
END PC_SEGUIMIENTOS;
/