---------------------------------------------------------------------------------------------------------------------------
                                              /*CICLO 1: CRUDE*/
---------------------------------------------------------------------------------------------------------------------------

/*SOLICITUD*/
CREATE OR REPLACE PACKAGE PC_SOLICITUDES IS
  PROCEDURE AD_SOLICITUD (xtid IN CHAR, xnid IN NUMBER, xprecio_min IN NUMBER, xprecio_max IN NUMBER);
  PROCEDURE MO_SOLICITUD (xnumero IN NUMBER, xprecio_max IN NUMBER);
  PROCEDURE EL_SOLICITUD (xnumero IN NUMBER);
  FUNCTION CO_SOLICITUD RETURN SYS_REFCURSOR;
  FUNCTION CO_ESTADO RETURN SYS_REFCURSOR;
END PC_SOLICITUDES;
/

/*OFERTA*/
CREATE OR REPLACE PACKAGE PC_OFERTAS IS
  PROCEDURE AD_OFERTA (xtid IN CHAR,xnid IN NUMBER,xprecioOferta IN NUMBER,xnegociable IN CHAR);
  PROCEDURE AD_ACTUALIZACION (xnumero IN NUMBER);
  PROCEDURE MO_OFERTA (xnumero IN NUMBER,xprecioOferta IN NUMBER);
  PROCEDURE EL_OFERTA (xnumero IN NUMBER);
  FUNCTION CO_ESTADO_OFERTA RETURN SYS_REFCURSOR;
END PC_OFERTAS;
/

/*PARTICIPANTE*/
CREATE OR REPLACE PACKAGE PC_PARTICIPANTES IS 
  PROCEDURE AD_PARTICIPANTE (xtid IN CHAR, xnid IN NUMBER, nombre IN VARCHAR2, apellido IN VARCHAR2, email IN VARCHAR2);
  PROCEDURE EL_PARTICIPANTE (xtid IN CHAR, xnid IN NUMBER);
  PROCEDURE AD_TELEFONO (xtid IN CHAR, xnid IN NUMBER, xnumero IN NUMBER);
END PC_PARTICIPANTES ;
/

/*FACTORMATCH*/
CREATE OR REPLACE PACKAGE PC_FactorMatch IS 
  FUNCTION CO_condicion RETURN SYS_REFCURSOR;
  FUNCTION CO_Tipopiso RETURN SYS_REFCURSOR;
  FUNCTION CO_habitacion RETURN SYS_REFCURSOR;
  FUNCTION CO_tipooferta RETURN SYS_REFCURSOR;
  FUNCTION CO_antiguedad RETURN SYS_REFCURSOR;
  FUNCTION CO_inmueble RETURN SYS_REFCURSOR;
  FUNCTION CO_estrato RETURN SYS_REFCURSOR;
  FUNCTION CO_area RETURN SYS_REFCURSOR;
END PC_FactorMatch;
/