---------------------------------------------------------------------------------------------------------------------------
                                              /*CICLO 1: ACTORESE*/
---------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PA_COMPRADOR IS
  PROCEDURE AD_SOLICITUD (xtid IN CHAR, xnid IN NUMBER, xprecio_min IN NUMBER, xprecio_max IN NUMBER);
  PROCEDURE MO_SOLICITUD (xnumero IN NUMBER, xprecio_max IN NUMBER);
  PROCEDURE EL_SOLICITUD (xnumero IN NUMBER);
  FUNCTION CO_SOLICITUD RETURN SYS_REFCURSOR;
  FUNCTION CO_ESTADO RETURN SYS_REFCURSOR;
  FUNCTION CO_condicion RETURN SYS_REFCURSOR;
  FUNCTION CO_Tipopiso RETURN SYS_REFCURSOR;
  FUNCTION CO_habitacion RETURN SYS_REFCURSOR;
  FUNCTION CO_tipooferta RETURN SYS_REFCURSOR;
  FUNCTION CO_antiguedad RETURN SYS_REFCURSOR;
  FUNCTION CO_inmueble RETURN SYS_REFCURSOR;
  FUNCTION CO_estrato RETURN SYS_REFCURSOR;
  FUNCTION CO_area RETURN SYS_REFCURSOR;
END PA_COMPRADOR;


CREATE OR REPLACE PACKAGE PA_VENDEDOR IS
  PROCEDURE AD_OFERTA(xtid IN CHAR,xnid IN NUMBER,xprecioOferta IN NUMBER,xnegociable IN CHAR);
  PROCEDURE AD_ACTUALIZACION(xnumero IN NUMBER);
  PROCEDURE MO_OFERTA(xnumero IN NUMBER,xprecioOferta IN NUMBER);
  PROCEDURE EL_OFERTA(xnumero IN NUMBER);
  FUNCTION CO_ESTADO_OFERTA RETURN SYS_REFCURSOR;
  FUNCTION CO_condicion RETURN SYS_REFCURSOR;
  FUNCTION CO_Tipopiso RETURN SYS_REFCURSOR;
  FUNCTION CO_habitacion RETURN SYS_REFCURSOR;
  FUNCTION CO_tipooferta RETURN SYS_REFCURSOR;
  FUNCTION CO_antiguedad RETURN SYS_REFCURSOR;
  FUNCTION CO_inmueble RETURN SYS_REFCURSOR;
  FUNCTION CO_estrato RETURN SYS_REFCURSOR;
  FUNCTION CO_area RETURN SYS_REFCURSOR;
END PA_VENDEDOR;

