---------------------------------------------------------------------------------------------------------------------------
                                              /*CICLO 1: ACTORESI*/
---------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY PA_COMPRADOR IS
    PROCEDURE AD_PROPUESTA (xtid IN CHAR, xnid IN NUMBER, xpropuesta IN VARCHAR2, xid_negocio IN NUMBER) IS
    BEGIN
        PC_PROPUESTAS.AD_PROPUESTA(xtid, xnid , xpropuesta, xid_negocio);
    END;
  
  PROCEDURE MO_PROPUESTA (xnumero IN NUMBER, xpropuesta IN VARCHAR2) IS
    BEGIN
        PC_PROPUESTAS.MO_PROPUESTA(xnumero, xpropuesta);
    END;

   FUNCTION CO_PROPUESTA RETURN SYS_REFCURSOR IS CO_PRO SYS_REFCURSOR;
    BEGIN
        CO_PRO:=PC_PROPUESTAS.CO_PROPUESTA;
    RETURN CO_PRO;
    END;
    
    PROCEDURE AD_DOCUMENTO (ximagen IN VARCHAR) IS
    BEGIN
        PC_DOCUMENTOS.AD_DOCUMENTO(ximagen);
    END;
    
    PROCEDURE AD_PROMESA(xnumero IN NUMBER, xinmueble IN VARCHAR, xid_comprador NUMBER, xid_vendedor NUMBER) IS
    BEGIN
        PC_DOCUMENTOS.AD_PROMESA(xnumero, xinmueble, xid_comprador, xid_vendedor);
    END;
    
    PROCEDURE AD_ESCRITURA (xnumero IN NUMBER, xevento IN CHAR) IS
    BEGIN
        PC_DOCUMENTOS.AD_ESCRITURA(xnumero, xevento);
    END;
  
  PROCEDURE MO_DOCUMENTO (xnumero IN NUMBER) IS
    BEGIN
        PC_DOCUMENTOS.MO_DOCUMENTO(xnumero);
    END;
    
    PROCEDURE EL_DOCUMENTO (xnumero IN NUMBER) IS
    BEGIN
        PC_DOCUMENTOS.EL_DOCUMENTO(xnumero);
    END;
    
    FUNCTION CO_DOCUMENTO RETURN SYS_REFCURSOR IS CO_DOC SYS_REFCURSOR;
    BEGIN
        CO_DOC:=PC_DOCUMENTOS.CO_DOCUMENTO;
    RETURN CO_DOC;
    END;
    FUNCTION CO_PROMESA RETURN SYS_REFCURSOR IS CO_PRO SYS_REFCURSOR;
    BEGIN
        CO_PRO:=PC_DOCUMENTOS.CO_PROMESA;
    RETURN CO_PRO;
    END;
    FUNCTION CO_ESCRITURA RETURN SYS_REFCURSOR IS CO_ESC SYS_REFCURSOR;
    BEGIN
        CO_ESC:=PC_DOCUMENTOS.CO_ESCRITURA;
    RETURN CO_ESC;
    END;
END PA_COMPRADOR;
/

CREATE OR REPLACE PACKAGE BODY PA_VENDEDOR IS
  PROCEDURE AD_NEGOCIO (xpropietario IN VARCHAR, xtitularidad IN VARCHAR, xuso IN VARCHAR, xfruto IN VARCHAR, xestadoJuridico IN XMLTYPE, xid_seguimiento IN NUMBER) IS
  BEGIN
    PC_NEGOCIOS.AD_NEGOCIO(xpropietario, xtitularidad, xuso, xfruto, xestadoJuridico, xid_seguimiento);
  END;
  
  PROCEDURE MO_NEGOCIO (xid_negocio IN NUMBER, xestadoJuridico IN XMLTYPE) IS
  BEGIN
    PC_NEGOCIOS.MO_NEGOCIO(xid_negocio, xestadoJuridico);
  END;
  
  FUNCTION CO_NEGOCIO RETURN SYS_REFCURSOR IS CO_NEG SYS_REFCURSOR;
  BEGIN
  CO_NEG:=PC_NEGOCIOS.CO_NEGOCIO;
  RETURN CO_NEG;
  END;
  
  FUNCTION CO_ESTADO_JURIDICO RETURN SYS_REFCURSOR IS CO_ESJ SYS_REFCURSOR;
  BEGIN
  CO_ESJ:=PC_NEGOCIOS.CO_ESTADO_JURIDICO;
  RETURN CO_ESJ;
  END;
  
  PROCEDURE AD_DOCUMENTO (ximagen IN VARCHAR) IS
    BEGIN
        PC_DOCUMENTOS.AD_DOCUMENTO(ximagen);
    END;
    
    PROCEDURE AD_PROMESA(xnumero IN NUMBER, xinmueble IN VARCHAR, xid_comprador NUMBER, xid_vendedor NUMBER) IS
    BEGIN
        PC_DOCUMENTOS.AD_PROMESA(xnumero, xinmueble, xid_comprador, xid_vendedor);
    END;
    
    PROCEDURE AD_ESCRITURA (xnumero IN NUMBER, xevento IN CHAR) IS
    BEGIN
        PC_DOCUMENTOS.AD_ESCRITURA(xnumero, xevento);
    END;
  
  PROCEDURE MO_DOCUMENTO (xnumero IN NUMBER) IS
    BEGIN
        PC_DOCUMENTOS.MO_DOCUMENTO(xnumero);
    END;
    
    PROCEDURE EL_DOCUMENTO (xnumero IN NUMBER) IS
    BEGIN
        PC_DOCUMENTOS.EL_DOCUMENTO(xnumero);
    END;
    
    FUNCTION CO_DOCUMENTO RETURN SYS_REFCURSOR IS CO_DOC SYS_REFCURSOR;
    BEGIN
        CO_DOC:=PC_DOCUMENTOS.CO_DOCUMENTO;
    RETURN CO_DOC;
    END;
    FUNCTION CO_PROMESA RETURN SYS_REFCURSOR IS CO_PRO SYS_REFCURSOR;
    BEGIN
        CO_PRO:=PC_DOCUMENTOS.CO_PROMESA;
    RETURN CO_PRO;
    END;
    FUNCTION CO_ESCRITURA RETURN SYS_REFCURSOR IS CO_ESC SYS_REFCURSOR;
    BEGIN
        CO_ESC:=PC_DOCUMENTOS.CO_ESCRITURA;
    RETURN CO_ESC;
    END;
END PA_VENDEDOR;
/

CREATE OR REPLACE PACKAGE BODY PA_ADMIN IS
  PROCEDURE AD_SEGUIMIENTO (xdocumento IN NUMBER, xfechafin DATE, xporcentaje IN NUMBER) IS
  BEGIN
    PC_SEGUIMIENTOS.AD_SEGUIMIENTO (xdocumento, xfechafin, xporcentaje);
  END;
  
  PROCEDURE MO_SEGUIMIENTO (xid_seguimiento IN NUMBER, xporcentaje IN NUMBER) IS
  BEGIN
    PC_SEGUIMIENTOS.MO_SEGUIMIENTO (xid_seguimiento, xporcentaje);
  END;
  
  PROCEDURE EL_SEGUIMIENTO (xid_seguimiento IN NUMBER) IS
  BEGIN
    PC_SEGUIMIENTOS.EL_SEGUIMIENTO(xid_seguimiento);
  END;
  
  FUNCTION CO_SEGUIMIENTO RETURN SYS_REFCURSOR IS CO_SEG SYS_REFCURSOR;
  BEGIN
  CO_SEG:=PC_SEGUIMIENTOS.CO_SEGUIMIENTO;
  RETURN CO_SEG;
  END;
  
  FUNCTION CO_SEG_POR RETURN SYS_REFCURSOR IS CO_SEP SYS_REFCURSOR;
  BEGIN
  CO_SEP:=PC_SEGUIMIENTOS.CO_SEG_POR;
  RETURN CO_SEP;
  END;
  
  FUNCTION CO_ACTIVO RETURN SYS_REFCURSOR IS CO_ACT SYS_REFCURSOR;
  BEGIN
  CO_ACT:=PC_SEGUIMIENTOS.CO_ACTIVO;
  RETURN CO_ACT;
  END;
END PA_ADMIN;